const SLOT_HIT_PAD = 28;

function mpIsActive(doc) {
  return doc.body.classList.contains('mp-game-active');
}

function cardUid(node) {
  const uid = Number(node?.dataset?.uid);
  return Number.isFinite(uid) ? uid : null;
}

function mpCardForUid(target, uid) {
  const state = target.tlrMpGetState?.();
  const myIndex = target.tlrMpGetRole?.() === 'host' ? 0 : 1;
  return (state?.players?.[myIndex]?.hand || []).find(card => card.uid === uid) || null;
}

function isValidSpreadDrop(doc, draggedCard) {
  const cardRect = draggedCard?.getBoundingClientRect?.();
  if (!cardRect) return false;
  const cardCX = cardRect.left + cardRect.width / 2;
  const cardCY = cardRect.top + cardRect.height / 2;

  for (const slot of doc.querySelectorAll('#spread .slot')) {
    if (slot.querySelector('.card')) continue;
    const rect = slot.getBoundingClientRect();
    if (cardCX >= rect.left - SLOT_HIT_PAD
      && cardCX <= rect.right + SLOT_HIT_PAD
      && cardCY >= rect.top - SLOT_HIT_PAD
      && cardCY <= rect.bottom + SLOT_HIT_PAD) return true;
  }
  return false;
}

function installMpHandReturnAdapter(target, doc) {
  if (target.__tlrMpHandReturnAdapterInstalled) return;
  target.__tlrMpHandReturnAdapterInstalled = true;

  let pendingSyntheticClickUid = null;

  target.addEventListener('click', event => {
    if (pendingSyntheticClickUid == null) return;
    const card = event.target?.closest?.('#hand .card[data-uid]');
    if (!card || cardUid(card) !== pendingSyntheticClickUid) return;
    pendingSyntheticClickUid = null;
    event.preventDefault?.();
    event.stopPropagation?.();
    event.stopImmediatePropagation?.();
  }, true);

  const finishNonPlacementDrag = event => {
    if (!mpIsActive(doc)) return;
    const draggedCard = doc.querySelector('.hand-card-dragging[data-uid]');
    if (!draggedCard) return;
    if (event.type !== 'pointercancel' && isValidSpreadDrop(doc, draggedCard)) return;

    const uid = cardUid(draggedCard);
    if (uid == null) return;
    const openDetail = event.type !== 'pointercancel'
      && draggedCard.classList.contains('hand-card-detail-pull');

    pendingSyntheticClickUid = uid;
    if (!target.tlrCancelHandDrag?.()) {
      pendingSyntheticClickUid = null;
      return;
    }

    // The shared controller normally keeps a broad 800ms click block after a
    // drag. Duel mode only needs to swallow the synthetic click generated by
    // this release, so the player's next real tap remains responsive.
    target.__handGestureSuppressClickUntil = 0;

    if (openDetail) {
      const card = mpCardForUid(target, uid);
      if (card) target.expandCard?.(card, target);
    }

    target.setTimeout?.(() => {
      if (pendingSyntheticClickUid === uid) pendingSyntheticClickUid = null;
    }, 0);

    event.preventDefault?.();
    event.stopImmediatePropagation?.();
  };

  // Run before gestureCard's document-capture pointerup handler. Valid spread
  // drops pass through untouched; every other duel drag uses the controller's
  // own cancel/FLIP return path and never enters the single-player hand store.
  target.addEventListener('pointerup', finishNonPlacementDrag, true);
  target.addEventListener('pointercancel', finishNonPlacementDrag, true);
}

function installDuelReferenceSurfaceStyle(doc) {
  if (doc.getElementById('mp-reference-surface-style')) return;
  const style = doc.createElement('style');
  style.id = 'mp-reference-surface-style';
  style.textContent = `
    body.mp-game-active #scoringPullTab,
    body.mp-game-active #abilitiesPullTab { display: none !important; }

    body.mp-game-active #scoringPullWrap > .spv2-menu-close-tab,
    body.mp-game-active #abilitiesPullWrap > .spv2-menu-close-tab {
      display: none !important;
      left: 50% !important;
      right: auto !important;
      transform: translateX(-50%) !important;
    }

    body.mp-game-active #scoringPullWrap.open > .spv2-menu-close-tab,
    body.mp-game-active #abilitiesPullWrap.open > .spv2-menu-close-tab {
      display: flex !important;
    }

    body.mp-game-active #titleWrap {
      z-index: 2147483100 !important;
    }

    body.mp-game-active #titleWrap .actions,
    body.mp-game-active #scoringBtn,
    body.mp-game-active #abilitiesBtn {
      z-index: auto !important;
    }

    body.mp-game-active #scoringPullWrap.open,
    body.mp-game-active #abilitiesPullWrap.open {
      z-index: 2147483250 !important;
    }
  `;
  doc.head.appendChild(style);
}

export function installMpAbilitySurfaceCleanup(target = window) {
  if (!target || target.__tlrMpAbilitySurfaceCleanupInstalled) return;
  target.__tlrMpAbilitySurfaceCleanupInstalled = true;
  const doc = target.document;
  if (!doc) return;
  installMpHandReturnAdapter(target, doc);
  installDuelReferenceSurfaceStyle(doc);
}
